django_construction/category/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.CategoryHome, name='category'),
    path('saveCategory/', views.save_categoryData, name='saveCategory'),
    path('deleteCategory/', views.delete_categoryData, name='deleteCategory'),
    path('editCategory/', views.edit_categoryData, name='editCategory'),

    path('subcategory/', views.SubCategoryHome, name='subcategory'),
    path('saveSubCategory/', views.save_subcategoryData, name='saveSubCategory'),
    path('deleteSubCategory/', views.delete_subcategoryData, name='deleteSubCategory'),
    path('editSubCategory/', views.edit_subcategoryData, name='editSubCategory'),
]

django_construction/product/urls.py
from django.urls import path
from .views import *



urlpatterns = [
    path('', ProductHome.as_view(), name='product'),
    path('productdata/', ProductData.as_view(), name='productdata'),
    path('createProduct/', save_productData.as_view(), name='createProduct'),
    path('delete_product/<int:product_id>/', DeleteProduct.as_view(), name='delete_product'),
    path('edit_product/<int:product_id>/', EditProduct.as_view(), name='edit_product'),
]

django_construction/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('authen.urls')),
    path("category/",include('category.urls')),
    path("supplier/",include('supplier.urls')),
    path("product/",include('product.urls')),
    path("contractor/",include('construction.urls')),
    path("purchase/",include('purchase.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django_construction/category/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=240)
    description = models.CharField(max_length=500, blank=True, null=True)
    status = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name




class SubCategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=240)
    description = models.CharField(max_length=500, blank=True, null=True)
    status = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

django_construction/category/forms.py
from django import forms
from .models import Category,SubCategory

class CategoryCreateForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'nameid'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'id': 'desid', 'rows': 3, 'cols': 1}),
        }


class SubCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['category','name', 'description']
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control', 'id': 'categoryid'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'nameid'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'id': 'desid', 'rows': 3, 'cols': 1}),
        }

django_construction/category/views.py
from django.http import JsonResponse
from django.shortcuts import render
from .forms import CategoryCreateForm, SubCategoryCreateForm
from .models import Category, SubCategory
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator

@login_required
def CategoryHome(request):
    form = CategoryCreateForm()
    categories = Category.objects.order_by('-created_at')

    # Set the number of items per page
    items_per_page = 10
    # Create a Paginator object with the categories queryset and items per page
    paginator = Paginator(categories, items_per_page)
    # Get the current page number from the request query parameters
    page_number = request.GET.get('page')
    # Get the Page object for the current page number
    page = paginator.get_page(page_number)

    return render(request, "categories/category.html", {'form':form,'categories':categories,'page': page})



@login_required
def save_categoryData(request):
    if request.method == "POST":
        form = CategoryCreateForm(request.POST)
        if form.is_valid():
            cid = request.POST['catid']
            name = request.POST['name']
            description = request.POST['description']
            user = request.user
            if(cid == ''):
                category = Category(name=name, description=description, user=user)
            else:
                category = Category.objects.get(id=cid)
                category.name = name
                category.description = description
                category.user = user
            category.save()
            cat = Category.objects.values()  #returns a QuerySet containing dictionaries
            print(cat)
            category_data = list(cat)
            return JsonResponse({'status':'save', 'category_data':category_data})
        else:
            return JsonResponse({'status':0})


@login_required
def delete_categoryData(request):
    if request.method == "POST":
        id = request.POST.get('cid')
        print(id)
        cat = Category.objects.get(pk=id)
        cat.delete()
        return JsonResponse({'status':1})
    else:
        return JsonResponse({'status':0})


@login_required
def edit_categoryData(request):
    if request.method == "POST":
        id = request.POST.get('cid')
        print(id)
        cat = Category.objects.get(pk=id)
        category_data ={"id":cat.id, "name":cat.name, "description":cat.description}
        return JsonResponse(category_data)
    

@login_required
def SubCategoryHome(request):
    form = SubCategoryCreateForm()
    subcategories = SubCategory.objects.order_by('-created_at')

    paginator = Paginator(subcategories, 15)  # Display 3 posts per page

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'form' : form,
        'page_obj': page_obj,
    }

    return render(request, "categories/subcategory.html", context)


@login_required
def save_subcategoryData(request):
    if request.method == "POST":
        form = SubCategoryCreateForm(request.POST)
        if form.is_valid():
            scid = request.POST['scatid']
            category_id = request.POST['category']
            name = request.POST['name']
            description = request.POST['description']
            user = request.user
            if(scid == ''):
                category = get_object_or_404(Category, id=category_id)
                subcategory = SubCategory(category=category, name=name, description=description, user=user)
            else:
                subcategory = SubCategory.objects.get(id=scid)
                category = get_object_or_404(Category, id=category_id)
                subcategory.category = category
                subcategory.name = name
                subcategory.description = description
                subcategory.user = user
            subcategory.save()
            # Get the SubCategory objects along with the related category
            subcategories = SubCategory.objects.select_related('category').all()
            subcategory_data = []
            for subcat in subcategories:
                data = {
                    'id': subcat.id,
                    'category': subcat.category.name,  # Access the category name
                    'name': subcat.name,
                    'description': subcat.description,
                    'status': subcat.status,
                }
                subcategory_data.append(data)
            return JsonResponse({'status':'save', 'subcategory_data':subcategory_data})
        else:
            return JsonResponse({'status':0})
        
    
@login_required
#@permission_required('category.delete_subcategory', raise_exception=True)
def delete_subcategoryData(request):
    if request.method == "POST":
        id = request.POST.get('scid')
        print(id)
        scat = SubCategory.objects.get(pk=id)
        scat.delete()
        return JsonResponse({'status':1})
    else:
        return JsonResponse({'status':0})
    

@login_required
def edit_subcategoryData(request):
    if request.method == "POST":
        id = request.POST.get('scid')
        print(id)
        scat = SubCategory.objects.get(pk=id)
        subcategory_data ={
            "id":scat.id,
            "category":scat.category.id, 
            "name":scat.name, 
            "description":scat.description
        }

        return JsonResponse(subcategory_data)
    

django_construction/templates/categories/category.html
{% extends "base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock title %}

{% block content %}


<!--start page wrapper -->
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Category</div>
        </div>
        <!--end breadcrumb-->
      
        <div class="card">
            <div class="card-body">
                <div class="d-lg-flex align-items-center mb-4 gap-3">
                    <div class="position-relative">
                        <input type="text" class="form-control ps-5 radius-30" placeholder="Search Order"> <span class="position-absolute top-50 product-show translate-middle-y"><i class="bx bx-search"></i></span>
                    </div>
                  <div class="ms-auto"><button class="btn btn-primary radius-30 mt-2 mt-lg-0" data-bs-toggle="modal" data-bs-target="#addCategoryModal">
                    <i class="bx bxs-plus-square"></i>Add Category</button></div>
                </div>
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>SL</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="tbodyid">
                            {% for cat in page %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ cat.name }}</td>
                                <td>{{ cat.description }}</td>
                                <td><div class="badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{ cat.status }}</div></td>
                                <td>
                                    <div class="d-flex order-actions">
                                        <a class="btn-edit" data-bs-toggle="modal" data-bs-target="#addCategoryModal" data-cid="{{cat.id}}"><i class='bx bxs-edit'></i></a>
                                        <a class="ms-3 btn-delete" data-cid="{{cat.id}}"><i class='bx bxs-trash'></i></a>
                                    </div>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5" class="text-center text-secondary my-5">No Record Found in Database</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <!-- Render the pagination links using Django's template tags -->
                    <div class="pagination mt-3">
                        {% if page.has_previous %}
                            <a class="btn btn-outline-primary mb-4" href="?page={{ page.previous_page_number }}">Previous</a>
                        {% endif %}
                        <span class="current">
                        <a class="btn btn-outline-primary mb-4"> Page {{ page.number }} of {{ page.paginator.num_pages }}.</a>
                        </span>
                        {% if page.has_next %}
                            <a class="btn btn-outline-primary mb-4" href="?page={{ page.next_page_number }}">Next</a>
                        {% endif %}

                        <p class="btn mb-4 float-end">Total: {{ page.paginator.count }} Data</p>
                    </div>
                </div>
            </div>
        </div>

        {% include "categories/modal/add_category.html" %}

    </div>
</div>
<!--end page wrapper -->
{% endblock content %}

{% block scripts %}
<script>
    $("#btnsave").click(function(e){
        e.preventDefault();
        console.log("Save Button Clicked !");
        output = "";
        let cid = $("#catid").val();
        let nm = $("#nameid").val();
        let des = $("#desid").val();
        let csrf = $("input[name=csrfmiddlewaretoken]").val();

        if(nm == ""){
            console.log("Please Fill Name!")
        }else{
            mydata = {catid:cid, name:nm, description:des, csrfmiddlewaretoken:csrf};
            $.ajax({
                url: "{% url 'saveCategory' %}",
                method: "POST",
                data:mydata,
                dataType: "json",
                success: function(data){
                    x = data.category_data ;
                    if(data.status == "save"){
                        toastr.success('Data Save Successfully');                   
                        for(i=0; i<x.length; i++)
                        {
                            output += "<tr><td>" +  (i+1) + "</td><td>" + x[i].name + 
                                "</td><td>" + x[i].description +
                                "</td><td><div class='badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3'><i class='bx bxs-circle me-1'></i>" + x[i].status + 
                                "</div></td><td><div class='d-flex order-actions'><a class='btn-edit' data-bs-toggle='modal' data-bs-target='#addCategoryModal' data-cid=" + x[i].id + 
                                "><i class='bx bxs-edit'></i></a><a class='ms-3 btn-delete' data-cid=" + x[i].id + 
                                "><i class='bx bxs-trash'></i></a></div>";

                            // Prepend the new row to the table
                            $("#tbodyid").prepend(output);
                        }

                        $("#categoryForm")[0].reset();
                        $("#addCategoryModal").modal('hide');
                        $("#tbodyid").html(output);
                    }
                    if(data.status == 0){
                        toastr.error('Data Save Error');
                        $('form')[0].reset();
                    }
                },
            });
        }

    });

    // Delete Data
    $("tbody").on("click",".btn-delete", function() {
        console.log("Delete btn clicked");
        let id = $(this).attr("data-cid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        mydata = {cid:id, csrfmiddlewaretoken:csrf};
        mythis = this;

        Swal.fire({
			title: 'Are you sure?',
			text: "You won't be able to revert this!",
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: 'Yes, delete it!'
		}).then((result) => {
		if (result.isConfirmed) {
			$.ajax({
            url: "{% url 'deleteCategory' %}",
            method: "POST",
            data:mydata,
            dataType: "json",
            success: function(data){
                if(data.status == 1){
                    toastr.success('Data Delete Successfully');
                    $(mythis).closest("tr").fadeOut();
                }else{
                    toastr.error('Data Delete Error');
                }
            }
            })
        }
		})

        
    })

    // Editing Data
    $("tbody").on("click",".btn-edit", function() {
        console.log("Edit btn clicked");
        let id = $(this).attr("data-cid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        mydata = {cid:id, csrfmiddlewaretoken:csrf};
        $.ajax({
            url: "{% url 'editCategory' %}",
            method: "POST",
            data:mydata,
            dataType: "json",
            success: function(data){
                console.log(data);
                $("#catid").val(data.id);
                $("#nameid").val(data.name);
                $("#desid").val(data.description);
                $("#btnsave").val("Update");
            }
        })
    })
</script>

{% endblock scripts %}

django_construction/templates/categories/subcategory.html
{% extends "base.html" %}
{% load static %}
{% block title %} Dashboard {% endblock title %}

{% block content %}

<!--start page wrapper -->
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Sub Category</div>
        </div>
        <!--end breadcrumb-->
      
        <div class="card">
            <div class="card-body">
                <div class="d-lg-flex align-items-center mb-4 gap-3">
                    <div class="position-relative">
                        <input type="text" class="form-control ps-5 radius-30" placeholder="Search Order"> <span class="position-absolute top-50 product-show translate-middle-y"><i class="bx bx-search"></i></span>
                    </div>
                    {% if perms.category.add_subcategory %}
                    <div class="ms-auto">
                        <button class="btn btn-primary radius-30 mt-2 mt-lg-0" data-bs-toggle="modal" data-bs-target="#addSubCategoryModal">
                            <i class="bx bxs-plus-square"></i>Add SubCategory
                        </button>
                    </div>
                    {% endif %}
                </div>
                <div class="table-responsive">
                    <table class="table mb-0">
                        <thead class="table-light">
                            <tr>
                                <th>SL</th>
                                <th>Category</th>
                                <th>Name</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="tbodyid">
                            {% for scat in page_obj %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{ scat.category }}</td>
                                <td>{{ scat.name }}</td>
                                <td>{{ scat.description }}</td>
                                <td><div class="badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3"><i class='bx bxs-circle me-1'></i>{{ scat.status }}</div></td>
                                <td>
                                    <div class="d-flex order-actions">
                                        {% if perms.category.change_category %}
                                            <a class="btn-edit" data-bs-toggle="modal" data-bs-target="#addSubCategoryModal" data-scid="{{scat.id}}">
                                                <i class='bx bxs-edit'></i>
                                            </a>
                                        {% endif %}
                                        {% if perms.category.delete_category %}
                                            <a class="ms-3 btn-delete" data-scid="{{scat.id}}">
                                                <i class='bx bxs-trash'></i>
                                            </a>
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="5" class="text-center text-secondary my-5">No Record Found in Database</td>
                            </tr>
                            {% endfor %}                            
                        </tbody>
                    </table>                    
                </div>

                <div class="pagination mt-3">
                    {% if page_obj.has_previous %}
                        <a class="btn btn-outline-primary mb-4" href="?page=1">First</a>
                        <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    {% endif %}
                
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <a class="btn btn-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}     
                            <a class="btn btn-outline-primary mb-4" href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
                
                    {% if page_obj.has_next %}
                        <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
                        <a class="btn btn-outline-primary mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
                    {% endif %}

                    <p class="btn mb-4 float-end">Total: {{ page_obj.paginator.count }} Data</p>
                </div>

            </div>
        </div>

        {% include "categories/modal/add_subCategory.html" %}

    </div>
</div>
<!--end page wrapper -->
{% endblock content %}

{% block scripts %}

<script>
    $("#btnsave").click(function(e){
        e.preventDefault();
        console.log("Save Button Clicked !");
        output = "";
        let scid = $("#scatid").val();
        let cid = $("#categoryid").val();
        let nm = $("#nameid").val();
        let des = $("#desid").val();
        let csrf = $("input[name=csrfmiddlewaretoken]").val();

        if(nm == ""){
            console.log("Please Fill Name!")
        }else{
            mydata = {scatid:scid,category:cid, name:nm, description:des, csrfmiddlewaretoken:csrf};
            $.ajax({
                url: "{% url 'saveSubCategory' %}",
                method: "POST",
                data:mydata,
                dataType: "json",
                success: function(data){
                   x = data.subcategory_data ;
                    if(data.status == "save"){
                        toastr.success('Data Save Successfully');                   
                        for(i=0; i<x.length; i++)
                        {
                            output += "<tr><td>" +  (i+1) + 
                                "</td><td>" + x[i].category + 
                                "</td><td>" + x[i].name + 
                                "</td><td>" + x[i].description +
                                "</td><td><div class='badge rounded-pill text-success bg-light-success p-2 text-uppercase px-3'><i class='bx bxs-circle me-1'></i>" + x[i].status + 
                                "</div></td><td><div class='d-flex order-actions'><a class='btn-edit' data-bs-toggle='modal' data-bs-target='#addSubCategoryModal' data-scid=" + x[i].id + 
                                "><i class='bx bxs-edit'></i></a><a class='ms-3 btn-delete' data-scid=" + x[i].id + 
                                "><i class='bx bxs-trash'></i></a></div>";

                        }

                        $("#subCategoryForm")[0].reset();
                        $("#addSubCategoryModal").modal('hide');
                        $("#tbodyid").html(output);
                    }
                    if(data.status == 0){
                        toastr.error('Data Save Error');
                        $('form')[0].reset();
                    }
                },
            });
        }

    });

    // Delete Data
    $("tbody").on("click",".btn-delete", function() {
        console.log("Delete btn clicked");
        let id = $(this).attr("data-scid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        mydata = {scid:id, csrfmiddlewaretoken:csrf};
        mythis = this;

        Swal.fire({
			title: 'Are you sure?',
			text: "You won't be able to revert this!",
			icon: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#3085d6',
			cancelButtonColor: '#d33',
			confirmButtonText: 'Yes, delete it!'
		}).then((result) => {
		if (result.isConfirmed) {
			$.ajax({
            url: "{% url 'deleteSubCategory' %}",
            method: "POST",
            data:mydata,
            dataType: "json",
            success: function(data){
                if(data.status == 1){
                    toastr.success('Data Delete Successfully');
                    $(mythis).closest("tr").fadeOut();
                }else{
                    toastr.error('Data Delete Error');
                }
            }
            })
        }
		})

        
    })


    // Editing Data
    $("tbody").on("click",".btn-edit", function() {
        console.log("Edit btn clicked");
        let id = $(this).attr("data-scid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        mydata = {scid:id, csrfmiddlewaretoken:csrf};
        $.ajax({
            url: "{% url 'editSubCategory' %}",
            method: "POST",
            data:mydata,
            dataType: "json",
            success: function(data){
                console.log(data);
                $("#scatid").val(data.id);
                $("#categoryid").val(data.category);
                $("#nameid").val(data.name);
                $("#desid").val(data.description);
                $("#btnsave").val("Update");
            }
        })
    })
</script>

{% endblock scripts %}